### ISSUE TITLE
Cannot install APK 1.0.2 on Android11

### ISSUE THREAD

**Issue by Test-Acount** [TheMegafuji/MegaAethric#1]
Cannot install APK 1.0.2 on Android11. Even fully reinstall. APK 1.0.1 works ok.

**Comment by Bredoz** [comment]
Same thing

**Comment by TheMegafuji** [comment]
just fixed this with an update on release apk:
https://github.com/TheMegafuji/MegaAethric/releases/tag/1.0.2
