### ISSUE TITLE
Intellectual property in repository

### ISSUE THREAD

**Issue by odierpg** [TheMegafuji/MegaAethric#15]
This repository includes our intellectual property and is uploaded under an MIT license, against Northern Forge Studios permission.

You cannot take anothers work and open source it.

Please remove this repository at your earliest convenience, before we need to pursue further action.

Thanks!

**Comment by Axibed** [comment]
> This repository includes our intellectual property and is uploaded under an MIT license, against Northern Forge Studios permission.
> 
> You cannot take anothers work and open source it.
> 
> Please remove this repository at your earliest convenience, before we need to pursue further action.
> 
> Thanks!

Hello dear developer,
Unfortunately I also used this repository and my account was blocked, 
Can you please restore my account? 
Axibed@mail.ru

**Comment by odierpg** [comment]
@TheMegafuji tagging to ensure you have scene this.

**Comment by TheMegafuji** [comment]
All IP and License of distribution were removed

**Comment by odierpg** [comment]
Property still remains at:

https://github.com/TheMegafuji/MegaAethric/releases

**Comment by TheMegafuji** [comment]
Removed

**Comment by odierpg** [comment]
Unfortunately, it looks like history was not removed.

The IP can still be accessed in git history: https://github.com/TheMegafuji/MegaAethric/blob/ee07c387e419e2f16beea927b6f9b6a2c068b491/assets/img/weapons/balor_staff.png

Some info removing files from history via filter-branch: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
