### ISSUE TITLE
Latest apk

### ISSUE THREAD

**Issue by Hklafiff** [TheMegafuji/MegaAethric#2]
Hello, sorry for this, its is possible to use the latest apk, from google play its 1.1.12

Thank you  🙇

![Screenshot_20230322_205847_Google Play Store](https://user-images.githubusercontent.com/127920371/226929501-dd1fa8fa-2a45-463a-8939-acd5c683d1c2.jpg)

**Comment by TheMegafuji** [comment]
The changes from the current version to the store versions are minor still, if something bigger launches I'll cover it, its not easy to migrate versions, its required to remake all the little changes. I'll keep an eye on the updates to consider migrating.
